// One-off hand-drawn pixel pictures (distinct icons, not recolour families).
// Loaded BEFORE pictures.js, which folds these into the picture library.
// Each entry: { id, name, category, palette, rows, difficulty? }  ('.' = background)
(function (root) {
  'use strict';
  const ONEOFFS = [
    // ===================== ANIMALS =====================
    { id: "a-fox", name: "Fox", category: "animals",
      palette: { ".": "#aee7ff", "o": "#f5824a", "w": "#fff4ea", "k": "#2b2230" },
      rows: ["..o........o..",".oo........oo.",".ooo......ooo.",".oooo....oooo.",".ooooooooooooo","ooowoooooowooo","oowwwooooowwwo","oowwwwoooowwwo",".owwwkoowkwwo.",".owwwwwwwwwwo.","..owwwkkwwwo..","...owwwwwwo...","....owwwwo....",".....oooo....."] },
    { id: "a-panda2", name: "Panda", category: "animals",
      palette: { ".": "#dff3e6", "w": "#ffffff", "k": "#2b2b32", "p": "#ff9bbf" },
      rows: [".kk........kk.",".kkk......kkk.",".kkkwwwwwwkkk.","..wwwwwwwwww..",".wwwwwwwwwwww.",".wwkkkwwkkkww.",".wwkkkwwkkkww.",".wwwwwwwwwwww.",".wwwwwkkwwwww.",".wwwwkkkkwwww.","..wwwwppwwww..","..wwwwwwwwww..","...wwwwwwww...",".....wwww....."] },
    { id: "a-bear", name: "Bear", category: "animals",
      palette: { ".": "#fff3f8", "b": "#9c6b3f", "t": "#d8a878", "k": "#34281c" },
      rows: [".bb........bb.","bbtb......btbb","bbtbbbbbbbbtbb",".bbbbbbbbbbbb.","bbbbbbbbbbbbbb","bbkkbbbbbbkkbb","bbkkbbbbbbkkbb","bbbbbbbbbbbbbb","bbbbttttttbbbb","bbbtttkktttbbb","bbbttkkkkttbbb",".bbttttttttbb.","..bbttttttbb..","...bbbbbbbb..."] },
    { id: "a-rabbit", name: "Rabbit", category: "animals",
      palette: { ".": "#dff3e6", "w": "#fefefe", "p": "#ffb4cf", "k": "#2c2630" },
      rows: ["..ww......ww..","..wpw....wpw..","..wpw....wpw..","..wpw....wpw..","..www....www..","...wwwwwwww...","..wwwwwwwwww..",".wwwwwwwwwwww.",".wwkkwwwwkkww.",".wwwwwppwwwww.",".wwwwwwwwwwww.","..wwwwwwwwww...","...wwwwwwww...","....wwwwww...."] },
    { id: "a-frog", name: "Frog", category: "animals",
      palette: { ".": "#dff3e6", "g": "#5fc24a", "w": "#ffffff", "k": "#22301a" },
      rows: ["..gg......gg..",".gwwg....gwwg.",".gwkg....gwkg.","ggggggggggggg","gggggggggggggg","gggggggggggggg","gggggggggggggg",".gggggggggggg.",".gggkkkkkkggg.","..gggggggggg..","gg.gggggggg.gg","ggg.gggggg.ggg",".gg........gg."] },
    { id: "a-pig", name: "Pig", category: "animals",
      palette: { ".": "#dff3e6", "p": "#ff9ec0", "P": "#f06fa0", "k": "#3a2030" },
      rows: ["..p........p..",".pp........pp.",".ppppppppppppp",".ppppppppppppp","pppppppppppppp","ppkkppppppkkpp","ppkkppppppkkpp","pppppppppppppp","ppppPPPPPPpppp","ppppPkPPkPpppp","ppppPPPPPPpppp",".pppppppppppp.","..pppppppppp..","...pppppppp..."] },
    { id: "a-cow", name: "Cow", category: "animals",
      palette: { ".": "#aee7ff", "w": "#ffffff", "k": "#2b2b32", "p": "#ffb4cf", "n": "#caa07a" },
      rows: [".nn........nn.","wnnw......wnnw","wwwwwwwwwwwwww","wwkkwwwwwwkkww","wkkkkwwwwkkkkw","wwwwwwwwwwwwww","wwwwkwwwwkwwww","wwwwwwwwwwwwww","wwkkwwwwwwkkww",".wwwwwwwwwwww.",".wwwppppppwww.",".wwpkppppkpww.",".wwwppppppwww.","..wwwwwwwwww.."] },
    { id: "a-chick", name: "Chick", category: "animals",
      palette: { ".": "#aee7ff", "y": "#ffe24a", "o": "#ff9a2e", "k": "#332a16" },
      rows: [".....yyyy.....","...yyyyyyyy...","..yyyyyyyyyy..",".yyyyyyyyyyyy.",".yyyyyyyyyyyy.",".yykkyyyykkyy.",".yykkyyyykkyy.",".yyyyooooyyyy.",".yyyyooooyyyy.","..yyyyyyyyyy..","...yyyyyyyy...","....oo..oo....","...oo....oo..."] },
    { id: "a-owl", name: "Owl", category: "animals",
      palette: { ".": "#0c1430", "b": "#7a5a3a", "t": "#caa070", "y": "#ffd23f", "k": "#1b1410" },
      rows: ["..bb......bb..",".bbbbbbbbbbbb.","bbbbbbbbbbbbbb","byyybbbbbbyyyb","bykybbbbbbykyb","byyybbbbbbyyyb","bbbbbyybbbbbbb","bbbbbyybbbbbbb","btttbbbbbtttbb","btttbbbbbtttbb","bbtttbbbtttbbb",".bbttttttttbb.","..bbbbbbbbbb..","...kk....kk..."] },
    { id: "a-penguin", name: "Penguin", category: "animals",
      palette: { ".": "#aee7ff", "k": "#26262e", "w": "#ffffff", "o": "#ff9a2e" },
      rows: ["....kkkkkk....","...kkkkkkkk...","..kkkkkkkkkk..","..kkwwwwwwkk..","..kwwwwwwwwk..","..kwwooooowwk.","..kwwowwowwk..",".kkwwwwwwwwkk.","kk.wwwwwwww.kk","k..wwwwwwww..k","...wwwwwwww...","...wwwwwwww...","...wwwwwwww...","...oo....oo..."] },
    { id: "a-lion", name: "Lion", category: "animals",
      palette: { ".": "#dff3e6", "m": "#c9772e", "y": "#f5c266", "k": "#3a2412", "n": "#8a4a1e" },
      rows: ["...mm.mmmm.mm...","..mmmmmmmmmmmm..",".mmmyyyyyyyymmm.","mmmyyyyyyyyyymmm","mmyyyyyyyyyyyymm","mmyykyyyyyykyymm","mmyykyyyyyykyymm","mmyyyyyyyyyyyymm","mmyyyynnyyyyymm.",".mmyyynnnnyyymm.",".mmmyykkkkyymmm.","..mmmyyyyyymmm..","...mmmmmmmmmm...","....mm....mm...."] },
    { id: "a-tiger", name: "Tiger", category: "animals",
      palette: { ".": "#dff3e6", "o": "#f59a3c", "k": "#2b2118", "w": "#fff4ea" },
      rows: [".ok........ko.",".oo........oo.","ooooooooooooo","okookoookooko","ooooooooooooo","owwooooooowwo","owwkoooookwwo","ooooowwoooooo","ooowwwwwwwooo","ooowkwwwkwooo",".oowwwwwwwwoo.",".ooowwkkwwooo.","..ooowwwwwoo..","...oooooooo..."] },
    { id: "a-monkey", name: "Monkey", category: "animals",
      palette: { ".": "#dff3e6", "b": "#8a5a32", "t": "#e0b888", "k": "#2c1c10" },
      rows: ["..bb......bb..",".bbbb....bbbb.",".bbtb....btbb.","..bbbbbbbbbb..",".bbbbbbbbbbbb.","bbttttttttttbb","bbtkttttttktbb","bbttttttttttbb",".bttttttttttb.",".bttkttttkttb.",".bttttkktttb..","..btttttttb...","...bbbbbbbb..."] },
    { id: "a-elephant", name: "Elephant", category: "animals",
      palette: { ".": "#dff3e6", "g": "#9aa6b2", "G": "#bfc8d2", "k": "#2c3038" },
      rows: ["....gggggg....","..gggggggggg..",".gggggggggggg.","gggggggggggggg","ggGggggggggGgg","gGGgggkkgggGGg","gGGggkkkkggGGg","gGGgggggggGGgg","gGGggggggggGgg","gGGgggggggggGg",".ggggggggggggg",".gggggggggggGg",".gg.gggg.gggGg",".gg.gggg.gggGg"] },
    { id: "a-snake", name: "Snake", category: "animals",
      palette: { ".": "#fff3f8", "g": "#5fbf4a", "G": "#9be07a", "k": "#22301a", "r": "#ff5a7a" },
      rows: ["..gggggggg....",".gGGGGGGGGg...","ggGGggggGGgg..","gGGg....gGGg..","ggg......ggg..","..........gggg",".......ggggGGg","....ggggGGGGgg","..ggggGGGGgg..",".gGGggggGg....","gGkrkGg.......","gGrrrGg.......",".gGGGg........","..ggg........."] },
    { id: "a-hedgehog", name: "Hedgehog", category: "animals",
      palette: { ".": "#dff3e6", "s": "#6a4a32", "t": "#e0b888", "k": "#2c1c10" },
      rows: ["....s.s.s.s...","...sssssssss..","..sssssssssss.",".sssssssssssss","sssssssssssttt","ssssssssssttkt","sssssssssstttt","ssssssssssttkt",".sssssssssttt.","..ssssssssst..","...t......t..."] },
    { id: "a-sheep", name: "Sheep", category: "animals",
      palette: { ".": "#aee7ff", "w": "#fefefe", "k": "#3a3340", "g": "#c9c2cc" },
      rows: ["..wwwwwwwwww..",".wwwwwwwwwwww.",".wwkwwwwwwkww.",".wkkkwwwwkkkw.",".wwkwwwwwwkww.","wwwwwwwwwwwwww","wwkkwwwwwwkkww","wwwwwwwwwwwwww","wwwwggggggwwww","wwwggkkkkgwwww",".wwgkggggkgww.","..wgg....ggw..","...g......g..."] },
    { id: "a-hamster", name: "Hamster", category: "animals",
      palette: { ".": "#dff3e6", "o": "#e8b870", "w": "#fff4e2", "k": "#3a2818", "p": "#ff9ec0" },
      rows: ["..oo......oo..",".oooo....oooo.",".oooooooooooo.","oooooooooooooo","oowwooooooowwoo","oowwoooooowwoo","ookkooooookkoo","ooowwwppwwwooo","oowwwwppwwwwoo",".owwwwkkwwwwo.",".owwwwwwwwwwo.","..owwwwwwwwo..","...oooooooo..."] },
    { id: "a-deer", name: "Deer", category: "animals",
      palette: { ".": "#dff3e6", "d": "#c98a52", "t": "#e8c098", "k": "#3a2414", "n": "#8a5a32" },
      rows: ["n.n......n.n","nnn......nnn",".nn..nn..nn.","..nn.nn.nn..","...nnnnnnn..","....dddd....","...dddddd...","..ddtttttd..","..dkdttdkd..","..ddtttttd..","..dddnnddd..","...dddddd...","....dddd...."] },
    { id: "a-raccoon", name: "Raccoon", category: "animals",
      palette: { ".": "#dff3e6", "g": "#8a909c", "w": "#f2f4f6", "k": "#26262e", "n": "#3a3a44" },
      rows: [".gg........gg.","ggggg....ggggg","gggggggggggggg","gggwwwwwwwwggg","ggwkkwwwwkkwgg","gwkkkkwwkkkkwg","gwwkkwwwwkkwwg","gggwwwwwwwwggg","ggggwwkkwwgggg","gggwwwkkwwwggg",".gggwwwwwwggg.","..gggggggggg..","...gg....gg..."] },
    { id: "a-giraffe", name: "Giraffe", category: "animals",
      palette: { ".": "#aee7ff", "y": "#f3c969", "o": "#c98a3c", "k": "#3a2a12", "n": "#8a5a24" },
      rows: [".....nn.n.....",".....yy.y.....",".....yoyy.....","......yyy.....","......kyk.....","......yyy.....",".....yyyy.....",".....yoyy.....","....yyyyoy....","...yyyyyyyy...","..yyoyyyyoyy..","..yyyyyyyyyy..","..yyoyyyoyyy..","..yyyyyyyyyy..","..yo.yy.yo.y..","..yy.yy.yy.y.."] },
    { id: "a-mouse", name: "Mouse", category: "animals",
      palette: { ".": "#dff3e6", "g": "#a7adba", "p": "#ffb4cf", "k": "#2c2630" },
      rows: ["..gg......gg..",".gppg....gppg.",".gppg....gppg.","..gggggggggg..",".gggggggggggg.","gggggggggggggg","ggkkggggggkkgg","gggggggggggggg","ggggggppgggggg","gggggpkkpggggg",".gggggppggggg.","..gggggggggg..","...gggggggg..."] },
    { id: "a-koala", name: "Koala", category: "animals",
      palette: { ".": "#dfeffb", "g": "#9aa0b0", "G": "#c2c8d6", "k": "#2b2b38", "n": "#3a3a48" },
      rows: ["..gg......gg..",".gGGg....gGGg.",".gGGggggggGGg.","gggggggggggggg","gggggggggggggg","ggkkggggggkkgg","ggkkggggggkkgg",".gggggnnggggg.","gggggnnnnggggg","ggggggnngggggg",".gggggggggggg.","..gggggggggg.."] },

    // ===================== SEA =====================
    { id: "s-octopus", name: "Octopus", category: "sea",
      palette: { ".": "#bfe8ff", "p": "#a55eea", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["....pppp....","..pppppppp..",".pppppppppp.",".pwkpppwkpp.",".pwkpppwkpp.",".pppppppppp.",".pppppppppp.","..pppppppp..",".p.p.p.p.p.p","p.p.p.p.p.p.","p..p...p..p."] },
    { id: "s-crab", name: "Crab", category: "sea",
      palette: { ".": "#bfe8ff", "r": "#ff5a3c", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["r..........r","rr...rr...rr",".rr.rrrr.rr.","..rrrrrrrr..",".rrwkrrkwrr.","rrrrrrrrrrrr","rrrrrrrrrrrr",".rr.rrrr.rr.","r.r.r..r.r.r"] },
    { id: "s-whale", name: "Whale", category: "sea",
      palette: { ".": "#bfe8ff", "b": "#3b6fd4", "w": "#ffffff", "k": "#1d1d2b" },
      rows: ["......w.....","....wwww....","...bbbbbb...","..bbbbbbbbb.",".bbbbbbbbbbb","bbkbbbbbbbbb","bbbbbbbbbbbb",".bbbbbbbbbb.","..wwwwwwww..",".....bb..bb."] },
    { id: "s-dolphin", name: "Dolphin", category: "sea",
      palette: { ".": "#bfe8ff", "b": "#5a9bd8", "w": "#ffffff", "k": "#1d1d2b" },
      rows: ["....b.......","...bbb......","...bbbbbb...","bb..bbbbbbbb","bbbbbbbbbbk.",".bbbbbbbbb..",".bbwwwbbb...","..bwwwwb....","...wwww.....","....ww......"] },
    { id: "s-seahorse", name: "Seahorse", category: "sea",
      palette: { ".": "#cdeeff", "y": "#ffb142", "k": "#1d1d2b", "o": "#e8852a" },
      rows: ["..yyy.......",".yyyyyy.....",".yykyyo.....","...yyyy.....","....yyy.....","....yyyo....","...oyyy.....","....yyy.....","....yyyo....","...oyyy.....","....yy......","...yyo......","...yy......."] },
    { id: "s-starfish", name: "Starfish", category: "sea",
      palette: { ".": "#bfe8ff", "o": "#ff9f1c", "y": "#ffe600", "k": "#1d1d2b" },
      rows: [".....oo.....",".....oo.....","....oooo....","o...oyyo...o","oo.oyyyyo.oo",".ooooyyoooo.","..oooyyooo..","..oookooo...",".ooo.oo.ooo.","oo...oo...oo","o...oo.oo..o"] },
    { id: "s-jellyfish", name: "Jellyfish", category: "sea",
      palette: { ".": "#cdeeff", "p": "#ff7eb6", "w": "#ffffff", "k": "#1d1d2b" },
      rows: ["...pppppp...","..pppppppp..",".pppppppppp.",".pwppppppwp.",".pwppppppwp.",".pppppppppp.",".pp.pp.pp.p.",".p.pp.pp.pp.","..p.pp.p.p..",".p.p.p.p.p..","..p..p..p..."] },
    { id: "s-shark", name: "Shark", category: "sea",
      palette: { ".": "#bfe8ff", "g": "#8a99a8", "w": "#ffffff", "k": "#1d1d2b" },
      rows: [".....g......","....gg......","...ggg......","..ggggggggg.",".gggggggggggg","gkggggggggwwg",".ggggggggwwwk","..gggggggggg.","...ggg..gg...","g...g........","gg.........."] },
    { id: "s-turtle", name: "Sea Turtle", category: "sea",
      palette: { ".": "#bfe8ff", "g": "#3fa34d", "d": "#2c7a3a", "y": "#a8d96a", "k": "#1d1d2b" },
      rows: ["....ggg.....","...gkggg....","..y.ggg.y...",".ggdgdgdgg..","gggdyddyggg.","ggdddddddgg.","gggdyddyggg.",".ggdgdgdgg..","..yggggggy..","..g.....g..."] },
    { id: "s-shell", name: "Shell", category: "sea",
      palette: { ".": "#cdeeff", "p": "#ff9ec4", "m": "#e85d9a", "w": "#ffffff" },
      rows: [".....ww.....","....pwwp....","...ppwwpp...","..pmppwppmp.",".pmppwwppmp.",".pmpwwwwpmp.","pmppwwwwppmp","pmpwwwwwwpmp","pmpwwwwwwpmp",".pmwwwwwwmp.","..pmmwwmmp..","...ppwwpp..."] },
    { id: "s-snail-sea", name: "Sea Snail", category: "sea",
      palette: { ".": "#bfe8ff", "o": "#ff8c42", "m": "#d96a2a", "y": "#ffd97d", "k": "#1d1d2b" },
      rows: ["............","....mmmm....","..mmoooomm..",".mmoymmyomm.",".moymoomyom.",".moymoomyom.",".mmoymmyomm.","yy.mmoooomm.","ykyyymmmmmm.","y..yyyyyyyyy","...yyyyyyyyy"] },
    { id: "s-lobster", name: "Lobster", category: "sea",
      palette: { ".": "#bfe8ff", "r": "#e63946", "d": "#b8232f", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["rr......rr..","rrr....rrr..",".rr....rr...","..rr..rr....","...rrrr.....","..rrwkrr....","..rrrrrr....","..drrrrd....","..rrrrrr....","..drrrrd....","..rrrrrr....","..rr..rr....",".rr....rr..."] },
    { id: "s-squid", name: "Squid", category: "sea",
      palette: { ".": "#bfe8ff", "p": "#ff6f91", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["....pppp....","...pppppp...","..pppppppp..","..pppppppp..","..pwkppwkp..","..pppppppp..","..pppppppp..","...pppppp...","..p.pp.pp.p.",".p.pp.pp.p..","p..p.pp.p..p","...p....p..."] },
    { id: "s-pufferfish", name: "Pufferfish", category: "sea",
      palette: { ".": "#bfe8ff", "y": "#ffcb47", "o": "#f08a24", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["..o..oo..o..","o.yo.yy.oy.o",".oyyyyyyyyo.","oyyyyyyyyyyo",".yywkyykwyy.","oyyyyyyyyyyo",".oyyyyyyyyo.","o.yo.yy.oy.o","..o..oo..o.."] },

    // ===================== BUGS =====================
    { id: "s-bee", name: "Bee", category: "bugs",
      palette: { ".": "#eef7ee", "y": "#ffcf33", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["....w..w....","....w..w....","..wwwyywww..",".wwykykykyww",".wwyyyyyyyww","..kyyyyyyk..","..ykkyykky..","..yyyyyyyy..","..kkyyyykk..","...kyyyyk...","....kkkk...."] },
    { id: "s-ladybug", name: "Ladybug", category: "bugs",
      palette: { ".": "#eef7ee", "r": "#e8323c", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["....kkkk....","...kkkkkk...","..kwk..kwk..",".rrrrkrrrr..","rrkrrkrrkrr.","rrrrrkrrrrr.","rrkrrkrrkrr.","rrrrrkrrrrr.",".rkrrkrrkr..","..rrrkrrr...","...rrkrr...."] },
    { id: "s-ant", name: "Ant", category: "bugs",
      palette: { ".": "#eef7ee", "k": "#5a3a22", "r": "#8a4b2a", "w": "#ffffff" },
      rows: ["k.k.........",".kk.........","..rrr.......",".rrwrr......","..rrr.rrr...","...r.rrrrr.rrr","..rrr.rrr.rrr.",".r.r.r.r.rrr..","r..r.r.r.r..r."] },
    { id: "s-spider", name: "Spider", category: "bugs",
      palette: { ".": "#eef7ee", "k": "#1d1d2b", "w": "#ffffff", "r": "#8a4b2a" },
      rows: ["k....kk....k",".k..kkkk..k.","..kkkkkkkk..","k.kkwkkwkk.k",".kkkkkkkkkk.","k.kkkkkkkk.k","..kkkkkkkk..",".k.kkkkkk.k.","k..k....k..k","..k......k.."] },
    { id: "s-dragonfly", name: "Dragonfly", category: "bugs",
      palette: { ".": "#eef7ee", "c": "#48cae4", "g": "#52b788", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["ccc....ccc..",".ccc..ccc...","..cckggkcc..","...ckwwkc...",".cccgggcccc.","...ckggkc...","..cckggkcc..",".ccc.gg.ccc.",".....gg.....",".....gg.....",".....gg.....","......g....."] },
    { id: "s-caterpillar", name: "Caterpillar", category: "bugs",
      palette: { ".": "#dff3e6", "g": "#7cc14a", "d": "#5a9e30", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["..kk........","..kk........",".gggg.......","gkwkg.gggg..","gwkwg.gddg.gggg","gggg.gddg.gddg.",".gg.gddg.gddg..","....gg.gddg.gg.",".....g.gg.g...."] },
    { id: "s-beetle", name: "Beetle", category: "bugs",
      palette: { ".": "#eef7ee", "g": "#2a9d8f", "d": "#1f7268", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["k...kk...k..",".k.kkkk.k...","..wkkkkw....",".ggdkkdgg...","ggggdkdgggg.","ggggdkdgggg.","gggdddddggg.",".ggdkkkdgg..","..gddkkdg...","..k.kk.k....",".k..kk..k..."] },
    { id: "s-worm", name: "Worm", category: "bugs",
      palette: { ".": "#dff3e6", "p": "#ff9ec4", "m": "#e8729e", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["........pppp",".......pwkpp",".......pwkpp",".pppp..pppp.","ppmmpp.pppp.","pmppmpppmpp.","pmppmppmppp.","ppmmppmppp..",".pppppppp..."] },
    { id: "s-snail-bug", name: "Garden Snail", category: "bugs",
      palette: { ".": "#dff3e6", "o": "#d98a3a", "m": "#a8632a", "y": "#f0c879", "k": "#1d1d2b" },
      rows: ["..k.k.......","..k.k.......","..kkk.mmmm..","...k.mmoomm.","..kkkmoyymom",".kyyymoyymom",".k..ymoyymom",".k..ymmoomm.",".kyyyymmmm..",".kyyyyyyyyyy","...yyyyyyyy."] },

    // ===================== FOOD =====================
    { id: "f-pizza", name: "Pizza Slice", category: "food",
      palette: { ".": "#fff3f8", "c": "#f4b740", "C": "#ffd97d", "r": "#ff4757", "g": "#2e8b46", "k": "#b5651d" },
      rows: [".....cc.....","....cCCc....","...cCrCCc...","...cCCCCc...","..cCgCCrCc..","..cCCCCCCc..",".cCrCCgCCrc.",".cCCCCCCCCc.","ccCCgCCrCCcc","ckkkkkkkkkkk",".kkkkkkkkkk."] },
    { id: "f-burger", name: "Burger", category: "food",
      palette: { ".": "#fff7e8", "b": "#e8a04f", "B": "#f4c17a", "m": "#7a3f1d", "g": "#2e8b46", "r": "#ff4757", "y": "#ffe600" },
      rows: ["...BBBBBB...",".BBBBBBBBBB.","BBBBBBBBBBBB","BBBBBBBBBBBB","gggggggggggg","rmmmmmmmmmmr","mmmmmmmmmmmm","yyyyyyyyyyyy","bBBBBBBBBBBb","bBBBBBBBBBBb",".bbbbbbbbbb."] },
    { id: "f-hotdog", name: "Hot Dog", category: "food",
      palette: { ".": "#fff7e8", "b": "#e8a04f", "B": "#f4c17a", "s": "#c0392b", "y": "#ffe600" },
      rows: ["............",".bbbbbbbbbb.","bBBBBBBBBBBb","bBssssssssBb","bsyssyssyssb","bBssssssssBb","bBssssssssBb","bBssyssyssBb","bBBBBBBBBBBb",".bbbbbbbbbb.","............"] },
    { id: "f-fries", name: "Fries", category: "food",
      palette: { ".": "#fff3f8", "r": "#ff4757", "R": "#ff6b81", "y": "#ffe600", "Y": "#ffd166" },
      rows: ["..y.y.y.y...",".yYyYyYyYy..",".yYyYyYyYy..",".yYyYyYyYy..","rRRRRRRRRRr.","rRrRrRrRrRr.","rRRRRRRRRRr.","rRrRrRrRrRr.","rRRRRRRRRRr.",".rRRRRRRRr..","..rrrrrrr..."] },
    { id: "f-sushi", name: "Sushi", category: "food",
      palette: { ".": "#eaf7ff", "k": "#1d1d2b", "w": "#ffffff", "r": "#ff6b81", "R": "#ff4757" },
      rows: ["............","...rRRRr....","..rRRRRRr...",".rRRRRRRRr..",".kwwwwwwwk..",".kwwwwwwwk..",".kwwwwwwwk..",".kwwwwwwwk..",".kkkkkkkkk..","............","............"] },
    { id: "f-taco", name: "Taco", category: "food",
      palette: { ".": "#fff7e8", "c": "#f4b740", "C": "#ffd97d", "g": "#7ed957", "r": "#ff4757", "m": "#7a3f1d" },
      rows: ["....CCCC....","..CCCCCCCC..",".CCCCCCCCCC.",".cgrgmgrmgc.","cgmgrgmgrgmc","cCggrgmgrgCc","cCCmgrgmrCCc","cCCCgrmgCCCc","cCCCCCCCCCCc",".cCCCCCCCCc.","..cccccccc.."] },
    { id: "f-fried-egg", name: "Fried Egg", category: "food",
      palette: { ".": "#eaf7ff", "w": "#ffffff", "W": "#f0f0f0", "y": "#ffd166", "Y": "#ffb700" },
      rows: ["............","...wwww.....","..wWWWWww...",".wWWyyWWWw..",".wWyYYyWWw..","wWWyYYyWWWw.","wWWWyyWWWWw.",".wWWWWWWWw..","..wWWWWWw...","...wwwww....","............"] },
    { id: "f-cookie", name: "Cookie", category: "food",
      palette: { ".": "#fff7e8", "b": "#c08552", "B": "#d9a066", "k": "#5a3921" },
      rows: ["...BBBBB....",".BBBBBBBBB..",".BkBBBBkBB..","BBBBBBBBBBB.","BBkBBBkBBBB.","BBBBBBBBBBB.","BkBBBkBBBkB.","BBBBBBBBBBB.",".BBkBBBBkB..",".BBBBBBBBB..","...BBBBB...."] },
    { id: "f-cake", name: "Cake Slice", category: "food",
      palette: { ".": "#fff3f8", "p": "#ff9ec7", "P": "#ffd0e4", "y": "#fff3c4", "r": "#ff4757", "b": "#c08552" },
      rows: [".......r....","......ppp...",".....pPPPp..","....yyyyyyy.","...PPPPPPPP.","..yyyyyyyyy.","..bbbbbbbbb.","..PPPPPPPPP.","..bbbbbbbbb.","..yyyyyyyyy.","..yyyyyyyyy."] },
    { id: "f-strawberry", name: "Strawberry", category: "food",
      palette: { ".": "#fff3f8", "g": "#2e8b46", "G": "#7ed957", "r": "#ff4757", "R": "#ff6b81", "y": "#ffe600" },
      rows: ["....gGg.....","...gGGGg....","..GrrRrrG...",".rRryrRyrRr.",".rryrrryrrr.",".RrrryrrrrR.",".rryrrryrrr.","..Rrryrrrr..","..rryrrryr..","...RrrrrR...","....rRr....."] },
    { id: "f-apple", name: "Apple", category: "food",
      palette: { ".": "#eaf7ff", "g": "#2e8b46", "b": "#7a3f1d", "r": "#ff4757", "R": "#ff6b81" },
      rows: [".....b......",".....bgg....","...RRRRR....","..RRrrrRR...",".RRrrrrrRR..",".RrrrrrrRR..",".Rrrrrrrrr..",".RrrrrrrrR..","..RrrrrrR...","..RRrrrRR...","...RrrrR...."] },
    { id: "f-banana", name: "Banana", category: "food",
      palette: { ".": "#fff3f8", "y": "#ffe600", "Y": "#ffd166", "k": "#7a3f1d" },
      rows: [".........k..","........kyk.",".......yyyY.","......yyyYY.","k....yyyYY..","ky..yyyYY...","kyyyyyyYY...",".kyyyyyYY...","..kyyyyY....","...kyyk.....","....kk......"] },
    { id: "f-grapes", name: "Grapes", category: "food",
      palette: { ".": "#fff7e8", "g": "#2e8b46", "p": "#8e44ad", "P": "#a569bd", "b": "#7a3f1d" },
      rows: ["......b.....","....ggbgg...","...gg...gg..","...PpPpPp...","..pPpPpPpP..","...pPpPpP...","...PpPpPp...","....pPpP....","....PpPp....",".....pP.....","......p....."] },
    { id: "f-cherries", name: "Cherries", category: "food",
      palette: { ".": "#fff3f8", "g": "#2e8b46", "b": "#7a3f1d", "r": "#ff4757", "R": "#ff6b81" },
      rows: ["........gg..",".......gg...","......gg.g..",".....gg..g..","...gbg...g..","..gg..g.gg..",".RRR..RRR...","RRrRR.RRrR..","RrrRR.RrrR..","RRRRR.RRRR..",".RRR...RRR.."] },
    { id: "f-carrot", name: "Carrot", category: "food",
      palette: { ".": "#eaf7ff", "g": "#2e8b46", "G": "#7ed957", "o": "#e8731f", "O": "#ff9a3c" },
      rows: ["....g.g.g...","....GgGgG...","....gGGGg...","....OOOO....","...OOoOOO...","...OoOOoO...","...OOOOO....","....OoOO....","....OOO.....",".....OO.....",".....O......"] },
    { id: "f-broccoli", name: "Broccoli", category: "food",
      palette: { ".": "#fff7e8", "g": "#2e8b46", "G": "#7ed957" },
      rows: ["...gg.gg....","..gGggGgg...",".gGgGgGgGg..","gGggGggGgGg.",".gGgGgGgGg..","..ggGggGg...","....GgG.....","....GgG.....","....GgG.....","....GGG.....","............"] },
    { id: "f-pretzel", name: "Pretzel", category: "food",
      palette: { ".": "#fff7e8", "b": "#8a5a2b", "B": "#b5651d", "s": "#ffffff" },
      rows: ["............","..BBB..BBB..",".BsBBBBBsB..",".BBBsBBsBB..","..BBBBBBB...","...BBsBB....","..BBBBBBB...",".BBBsBsBBB..",".BBBBBBBBB..","..BBB.BBB...","............"] },
    { id: "f-coffee", name: "Coffee Cup", category: "food",
      palette: { ".": "#fff3f8", "w": "#ffffff", "W": "#e0e0e0", "k": "#5a3921", "s": "#cfcfe0" },
      rows: ["..s..s..s...","...s..s.....","wwwwwwwwww..","wkkkkkkkkw..","wkkkkkkkkwW.","wWWWWWWWWwW.","wWWWWWWWWwW.","wWWWWWWWWw..",".wWWWWWWw...","..wwwwww....","............"] },
    { id: "f-milkshake", name: "Milkshake", category: "food",
      palette: { ".": "#eaf7ff", "p": "#ff9ec7", "P": "#ffd0e4", "r": "#ff4757", "w": "#ffffff", "s": "#cfcfe0" },
      rows: [".....r......","...PPPPP....","..PpPpPpP...","..PPPPPPP...","...sssss....","...wPwPw....","...wwwww....","...wPwPw....","....www.....","....www.....",".....w......"] },
    { id: "f-pancakes", name: "Pancakes", category: "food",
      palette: { ".": "#fff3f8", "b": "#e8a04f", "B": "#f4c17a", "y": "#ffd166", "k": "#b5651d" },
      rows: ["............","....yyyy....","..yyBBBByy..",".bBBBBBBBBb.",".bBkBBBkBBb.",".bBBBBBBBBb.",".bBBkBBBBBb.",".bBBBBBBkBb.",".bBBBBBBBBb.","..bbbbbbbb..","............"] },
    { id: "f-croissant", name: "Croissant", category: "food",
      palette: { ".": "#eaf7ff", "b": "#c4862c", "B": "#f4c17a", "k": "#8a5a2b" },
      rows: ["............","..bb....bb..",".bBBb..bBBb.",".bBBBbbBBBb.","bBBkBBBBkBBb","bBBBBBBBBBBb","bBkBBBBBBkBb",".bBBBBBBBBb.",".bBBkBBkBBb.","..bBBBBBBb..","...bbbbbb..."] },
    { id: "f-orange", name: "Orange", category: "food",
      palette: { ".": "#eaf7ff", "g": "#2e8b46", "o": "#e8731f", "O": "#ff9a3c" },
      rows: [".....g......","....OOO.....","..OOOOOOO...",".OOOoOoOOO..",".OOoOOOoOO..","OOOOOoOOOOO.",".OOoOOOoOO..",".OOOoOoOOO..","..OOOOOOO...","....OOO.....","............"] },
    { id: "f-pear", name: "Pear", category: "food",
      palette: { ".": "#eaf7ff", "g": "#2e8b46", "b": "#7a3f1d", "y": "#c6e377", "Y": "#a8d44a" },
      rows: [".....b......",".....bg.....",".....Y......","....YyY.....","....YyY.....","...YyyyY....","..YyyyyyY...","..YyyyyyY...","..YyyyyyY...","...YyyyY....","....YYY....."] },
    { id: "f-pineapple", name: "Pineapple", category: "food",
      palette: { ".": "#fff3f8", "g": "#2e8b46", "G": "#7ed957", "y": "#ffd166", "k": "#b5651d" },
      rows: ["...G.G.G....","..GgGgGg....","...GgGgG....","..ykykyk....",".ykykykyk...",".kykykyky...",".ykykykyk...",".kykykyky...",".ykykykyk...","..kykyky....","...kkyk....."] },
    { id: "f-corn", name: "Corn", category: "food",
      palette: { ".": "#eaf7ff", "g": "#2e8b46", "G": "#7ed957", "y": "#ffe600", "Y": "#ffd166" },
      rows: [".....y......","....yYy.....","...gyYyg....","..GyYyYyG...","..yYyYyYy...","..YyYyYyY...","..yYyYyYy...","..YyYyYyY...","...yYyYy....","....yYy.....",".....y......"] },
    { id: "f-bread", name: "Bread Loaf", category: "food",
      palette: { ".": "#fff7e8", "b": "#c4862c", "B": "#e8a04f", "k": "#8a5a2b" },
      rows: ["............","..bbbbbbbb..",".bBBBBBBBBb.","bBBBBBBBBBBb","bBkBkBkBkBBb","bBBBBBBBBBBb","bBBBBBBBBBBb","bBBBBBBBBBBb","bBBBBBBBBBBb",".bbbbbbbbbb.","............"] },

    // ===================== VEHICLES =====================
    { id: "v-train", name: "Train", category: "vehicles",
      palette: { ".": "#eaf7ff", "r": "#e63946", "b": "#1d3557", "y": "#ffd200", "k": "#2b2b2b", "g": "#bfe9ff" },
      rows: ["....bbbb....","...bbbbbb...","...bggggb...","...bggggb...","..rrrrrrrr..",".rrrrrrrrrr.",".rryggyggrr.",".rrrrrrrrrr.",".rrrrrrrrrr.","krrrrrrrrrrk",".kk..kk..kk.",".kk..kk..kk."] },
    { id: "v-plane", name: "Plane", category: "vehicles",
      palette: { ".": "#eaf7ff", "w": "#eef0f5", "b": "#1d6fb8", "g": "#bfe9ff", "k": "#2b2b2b" },
      rows: ["......ww......",".....wwww.....","....wwggww....","...wwwggwww...","bbwwwwwwwwwwbb","bbbwwwwwwwwbbb","..wwwwwwwwww..","...wwwwwwww...","....wwwwww....",".....wkkw.....","....wkkkkw....","....kk..kk...."] },
    { id: "v-sailboat", name: "Sailboat", category: "vehicles",
      palette: { ".": "#eaf7ff", "w": "#ffffff", "r": "#e63946", "h": "#8a5a2b", "b": "#1d6fb8" },
      rows: [".....r......",".....ww.....",".....www....",".....wwww...",".....wwwww..",".....wwwwww.","....rwwwwww.","...rrwwwwww.","....r.......",".hhhhhhhhhh.","..hhhhhhhh..",".bbbbbbbbbb."] },
    { id: "v-bus", name: "Bus", category: "vehicles",
      palette: { ".": "#eaf7ff", "y": "#ffd200", "g": "#bfe9ff", "k": "#2b2b2b", "r": "#e63946" },
      rows: [".yyyyyyyyyy.","yyyyyyyyyyyy","yggyggyggyyy","yggyggyggyyy","yyyyyyyyyyyy","yyyyyyyyyyyy","yrrrrrrrrrry","yyyyyyyyyyyy","yyyyyyyyyyyy","kkyyyyyykkyy",".kk....kk...","............"] },
    { id: "v-bicycle", name: "Bicycle", category: "vehicles",
      palette: { ".": "#eaf7ee", "k": "#2b2b2b", "r": "#e63946" },
      rows: ["............",".....rr.....","....r..r....","...r....rkk.","..rrrrrrk...",".kkk..rrk...","kk.kkrrkkk..","k...k..k..k.","kk.kkk.kk.kk","k.k.k.k.k.k.","kk.kk...kk.k","k...k....k.."] },
    { id: "v-truck", name: "Truck", category: "vehicles",
      palette: { ".": "#eaf7ff", "b": "#1d6fb8", "g": "#bfe9ff", "w": "#eef0f5", "k": "#2b2b2b" },
      rows: ["............","wwwwwww.....","wwwwwww.....","wwwgggw.....","wwwgggwbbbbb","wwwwwwwbbbbb","wwwwwwwbbbbb","wwwwwwwbbbbb","wwwwwwwbbbbb","kkkwwwkkkbbb",".kk.k.kk....","............"] },
    { id: "v-helicopter", name: "Helicopter", category: "vehicles",
      palette: { ".": "#eaf7ff", "k": "#2b2b2b", "r": "#e63946", "g": "#bfe9ff" },
      rows: ["kkkkkkkkkkkk",".....k......",".....k......","..rrrrr.....",".rrgggrr....","rrrgggrrrrk.","rrrrrrrrrrk.",".rrrrrr.....","..k...k.....",".kkk.kkk....","............","............"] },
    { id: "v-tractor", name: "Tractor", category: "vehicles",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "y": "#ffd200", "k": "#2b2b2b", "b": "#bfe9ff" },
      rows: ["............","...ggg......","..gbbbg.....","..gbbbg.gg..","..gggggggg..",".ggggggggg..",".ggggggggg..","kkkkgggggg..","kbbkggkkkk..","kbbkgkbbbk..","kkkk.kbbbk..",".....kkkk..."] },
    { id: "v-police", name: "Police Car", category: "vehicles",
      palette: { ".": "#eaf7ff", "w": "#eef0f5", "b": "#1d3557", "r": "#e63946", "g": "#bfe9ff", "k": "#2b2b2b" },
      rows: ["............","....rb......","...wwwwww...","..wwggggww..",".wwwwwwwwww.","bbbbbbbbbbbb","wwbbbbbbbbww","wwwwwwwwwwww","wwwwwwwwwwww","kkkwwwwwwkkk",".kk......kk.","............"] },
    { id: "v-fireengine", name: "Fire Engine", category: "vehicles",
      palette: { ".": "#eaf7ff", "r": "#e63946", "g": "#bfe9ff", "y": "#ffd200", "k": "#2b2b2b", "w": "#eef0f5" },
      rows: ["....y.......","....y.......","rrrrrrrr....","rrggggrrrrrr","rrggggrwwwwr","rrrrrrrwwwwr","rrrrrrrrrrrr","ryyyyyyyyyyr","rrrrrrrrrrrr","kkkrrrrkkkrr",".kk....kk...","............"] },
    { id: "v-scooter", name: "Scooter", category: "vehicles",
      palette: { ".": "#eaf7ee", "k": "#2b2b2b", "t": "#19b3c4", "g": "#bfe9ff" },
      rows: ["............","......kk....",".....kk.....",".....k......",".ttttk......","tt..tk......","t.tttk......","t.t..k......","ttt.kkkkkk..",".kkk.....k..","kkkkk..kkkk.","k...k..k..k."] },
    { id: "v-submarine", name: "Submarine", category: "vehicles",
      palette: { ".": "#dff1ff", "y": "#ffd200", "k": "#2b2b2b", "g": "#bfe9ff", "r": "#e63946" },
      rows: [".....rr.....",".....yy.....",".....yy.....","..yyyyyyy...",".yyyyyyyyyy.","yyygyyygyyyy","yyygyyygyyyk",".yyyyyyyyyy.","..yyyyyyy...","............","............","............"] },

    // ===================== SPACE =====================
    { id: "sky-astronaut", name: "Astronaut", category: "space",
      palette: { ".": "#0a0a23", "w": "#eef0f5", "g": "#3aa6ff", "k": "#2b2b2b" },
      rows: ["....wwww....","...wwwwww...","..wwggggww..","..wwggggww..","..wwggggww..","...wwwwww...","..wwwwwwww..",".wwwwwwwwww.","wwwwwwwwwwww","wwwwwwwwwwww",".wwww..wwww.",".ww......ww."] },
    { id: "sky-satellite", name: "Satellite", category: "space",
      palette: { ".": "#0a0a23", "b": "#1d6fb8", "y": "#ffd200", "w": "#eef0f5", "k": "#9aa0aa" },
      rows: ["............",".bbb....bbb.",".byb.ww.byb.",".bbbwwwwbbb.",".byb.ww.byb.",".bbb.ww.bbb.","....wwww....","...wwwwww...","....wwww....",".....kk.....",".....kk.....","............"] },
    { id: "sky-comet", name: "Comet", category: "space",
      palette: { ".": "#0a0a23", "y": "#ffd200", "o": "#ff8c1a", "w": "#bfe9ff" },
      rows: ["..........yy","........yyyy",".......oyyy.","ww....ooyy..",".wwwwooyy...","...wwoooy...",".wwwwooyy...","wwww.ooyy...","......oyyy..","........yyy.","..........y.","............"] },
    { id: "sky-shootingstar", name: "Shooting Star", category: "space",
      palette: { ".": "#0c1430", "y": "#ffd200", "w": "#bfe9ff" },
      rows: ["..........y.",".........yyy","........yyy.","wwww...y.y..",".wwwwwy.....","...wwwww....",".wwwwwy.y...","wwww..yyy...",".......yyy..","........y...","............","............"] },
    { id: "sky-saturn", name: "Saturn", category: "space",
      palette: { ".": "#0a0a23", "o": "#ffb14a", "y": "#ffe08a", "r": "#ff8c1a" },
      rows: ["............","....oooo....","..oooyyooo..","..oyyyyyoo..","rroooyyooorr",".rroooooorr.","...rrrrr....","..oooooooo..","...oooooo...",".....oo.....","............","............"] },
    { id: "sky-shuttle", name: "Space Shuttle", category: "space",
      palette: { ".": "#0a0a23", "w": "#eef0f5", "r": "#e63946", "o": "#ff8c1a", "g": "#bfe9ff" },
      rows: [".....ww.....",".....ww.....","....wggw....","....wwww....","...wwwwww...","..wwwwwwww..",".rwwwwwwwwr.","rrwwwwwwwwrr","rr.wwwwww.rr","....oooo....","...oo..oo...","..oo....oo.."] },
    { id: "sky-alien", name: "Alien", category: "space",
      palette: { ".": "#0a0a23", "g": "#3ad14a", "w": "#eef0f5", "k": "#0c1430" },
      rows: ["............","...gggggg...","..gggggggg..",".gggggggggg.",".gwwggggwwg.",".gwkggggkwg.",".gggggggggg.","..gggggggg..","...g.gg.g...","..g..gg..g..",".g...gg...g.","............"] },

    // ===================== NATURE =====================
    { id: "nat-sun", name: "Sun", category: "nature",
      palette: { ".": "#eaf7ff", "y": "#ffd200", "o": "#ff8c1a" },
      rows: ["...y..y..y..","....y.y.y...","y...ooooo..y",".y.ooyyyoo.y","..ooyyyyyoo.",".oooyyyyyooo","yooyyyyyyyoy",".oooyyyyyooo","..ooyyyyyoo.",".y.ooyyyoo.y","y...ooooo..y","....y.y.y..."] },
    { id: "nat-rainbow", name: "Rainbow", category: "nature",
      palette: { ".": "#eaf7ff", "r": "#e63946", "o": "#ff8c1a", "y": "#ffd200", "g": "#2a9d4a", "b": "#1d6fb8" },
      rows: ["............","...rrrrrr...","..rroooorr..",".rooyyyyoor.","rooyyggyyoor","rooyggbbggor","rooyggbbggor","rryyggbbggyr","....bbbb....","............","............","............"] },
    { id: "nat-cloud", name: "Cloud", category: "nature",
      palette: { ".": "#dff1ff", "w": "#ffffff", "g": "#cfe4f5" },
      rows: ["............","............","....wwww....","...wwwwww...","..wwwwwwww..",".wwwwwwwwww.","wwwwwwwwwwww","wwwwwwwwwwww","ggwwwwwwwwgg","..gggggggg..","............","............"] },
    { id: "nat-raincloud", name: "Rain Cloud", category: "nature",
      palette: { ".": "#dff1ff", "w": "#9aa0aa", "d": "#6a7079", "b": "#1d6fb8" },
      rows: ["....wwww....","...wwwwww...","..wwwwwwww..",".wwwwwwwwww.","wwwwwwwwwwww","ddwwwwwwwwdd","..dddddddd..","..b..b..b...",".b..b..b..b.","..b..b..b...",".b..b..b..b.","............"] },
    { id: "nat-pinetree", name: "Pine Tree", category: "nature",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "d": "#1e7035", "h": "#8a5a2b" },
      rows: [".....gg.....","....gggg....","....gddg....","...gggggg...","..ggggdggg..","..gggggggg..",".gggggddggg.",".gggggggggg.","gggggddggggg","gggggggggggg",".....hh.....",".....hh....."] },
    { id: "nat-roundtree", name: "Round Tree", category: "nature",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "d": "#1e7035", "h": "#8a5a2b" },
      rows: ["...gggggg...","..gggggggg..",".gggdggggdg.","gggggggggggg","ggdgggggggdg","gggggggggggg","gggggdggdggg",".gggggggggg.","..gggggggg..","....hhhh....","....hhhh....","....hhhh...."] },
    { id: "nat-palmtree", name: "Palm Tree", category: "nature",
      palette: { ".": "#eaf7ff", "g": "#2a9d4a", "h": "#8a5a2b", "o": "#ff8c1a" },
      rows: ["..gg....gg..",".gggg..gggg.","gggggggggggg",".ggg.oo.ggg.","...ghhhhg...","....hhhh....","....hhhh....","...hhhh.....","...hhhh.....","..hhhh......","..hhhh......",".hhhh......."] },
    { id: "nat-cactus", name: "Cactus", category: "nature",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "d": "#1e7035", "y": "#ffd200" },
      rows: ["............",".gg......gg.",".gg..gg..gg.",".gg..gg..gg.",".ggg.gg.ggg.","..gggggggg..","...gggggg...","....gggg....","....gygg....","....gggg....","....gggg....","..dddddddd.."] },
    { id: "nat-leaf", name: "Leaf", category: "nature",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "d": "#1e7035", "h": "#8a5a2b" },
      rows: [".........gg.","........ggg.",".......gggg.","..ggg.ggddg.",".ggggggddgg.","gggggddgggg.","ggggddggggg.",".gggddgggg..",".ggddgggg...","..ddgg......",".hh.........","hh.........."] },
    { id: "nat-clover", name: "Four-Leaf Clover", category: "nature",
      palette: { ".": "#eaf7ee", "g": "#2a9d4a", "d": "#1e7035", "h": "#8a5a2b" },
      rows: ["............",".ggg..ggg...","ggggg.ggggg.","ggdgg.ggdgg.","ggggg.ggggg.",".gggg.gggg..","...gg.gg....",".gggg.gggg..","ggggg.ggggg.","ggdgg.ggdgg.",".ggg.h.ggg..",".....h......"] },
    { id: "nat-sunflower", name: "Sunflower", category: "nature",
      palette: { ".": "#eaf7ee", "y": "#ffd200", "o": "#ff8c1a", "g": "#2a9d4a", "h": "#8a5a2b" },
      rows: ["...y.yy.y...","..yyyyyyyy..",".yyooooooyy.",".yoooooooy..","yyooooooooyy","yyooooooooyy",".yoooooooy..",".yyooooooyy.","..yyyyyyyy..","....ghg.....","....ghg.....","...gghgg...."] },
    { id: "nat-lightning", name: "Lightning Bolt", category: "nature",
      palette: { ".": "#eaf7ff", "y": "#ffd200", "o": "#ff8c1a" },
      rows: [".......yyy..","......yyy...",".....yyy....","....oyy.....","...yyyyyyy..","..yyyyyyy...",".....yyy....","....yyy.....","...yyo......","..yyy.......",".yyy........","............"] },
    { id: "nat-mountain", name: "Mountain", category: "nature",
      palette: { ".": "#dff1ff", "g": "#6a7079", "d": "#4a4f57", "w": "#ffffff" },
      rows: ["............",".....g......","....www.....","....wgw.....","...ggggg.gg.","..gggwgggwwg",".gggdgggwggg",".ggdgggggggg","gggggdggggdg","gggdgggggggg","ggggggdggggg","gggggggggggg"] },
    { id: "nat-acorn", name: "Acorn", category: "nature",
      palette: { ".": "#eaf7ee", "h": "#8a5a2b", "d": "#5c3a1a", "t": "#c98a4a" },
      rows: [".....d......","....ddd.....","..dddddddd..",".dddddddddd.",".dddddddddd.","..tttttttt..","..tthtttht..","..tttttttt..","..ttthhttt..","...tttttt...","....tttt....",".....tt....."] },

    // ===================== HOLIDAYS =====================
    { id: "h-christmas-tree", name: "Christmas Tree", category: "holidays",
      palette: { ".": "#eaf7ff", "g": "#2e8b57", "y": "#ffe600", "n": "#8b5a2b", "r": "#ff2e88" },
      rows: ["......yy......",".....yyyy.....","......gg......",".....gggg.....","....gggggg....","...rggggggr...","....gggggg....","...gggggggg...","..rggggggggr..",".gggggggggggg.","...gggggggg...","......nn......","......nn......"] },
    { id: "h-snowman", name: "Snowman", category: "holidays",
      palette: { ".": "#0c1430", "w": "#ffffff", "k": "#1d1d2b", "o": "#ff8c00", "r": "#ff2e88" },
      rows: ["....kkkkkk....","....kkkkkk....","...wwwwwwww...","..wwkkwwkkww..","..wwwwoowwww..","..wwwrrrrwww..","...wwwwwwww...","..wwwwwwwwww..",".wwwkwwwwkwww.",".wwwwwwwwwwww.",".wwwwkwwkwwww.",".wwwwwwwwwwww.","..wwwwwwwwww.."] },
    { id: "h-santa-hat", name: "Santa Hat", category: "holidays",
      palette: { ".": "#eaf7ff", "r": "#c0392b", "w": "#ffffff" },
      rows: ["..........ww..",".........wwww.",".......wwwwww.",".....rrrwwww..","...rrrrrrww...","..rrrrrrrr....",".rrrrrrrrr....",".rrrrrrrrrr...","rrrrrrrrrrrr..","wwwwwwwwwwwwww","wwwwwwwwwwwwww"] },
    { id: "h-candy-cane", name: "Candy Cane", category: "holidays",
      palette: { ".": "#eaf7ff", "r": "#c0392b", "w": "#ffffff" },
      rows: ["...rrwww......","..rwwwwrr.....",".rwww..rww....",".rww....rw....",".rw.....rw....","........wr....",".......rrw....",".......rww....",".......wwr....",".......rrw....",".......rww....",".......wwr....",".......rrw...."] },
    { id: "h-jack-o-lantern", name: "Jack-o-Lantern", category: "holidays",
      palette: { ".": "#0c1430", "o": "#ff8c00", "g": "#2e8b57", "k": "#1d1d2b" },
      rows: [".....gg.......",".....gg.......","...oooooooo...","..oooooooooo..",".oooooooooooo.",".okkooooookko.",".okkooooookko.",".oooookkoooooo",".okoooooooooko",".okkokkkkokko.",".ookkkkkkkkoo.","..oooooooooo..","...oooooooo..."] },
    { id: "h-turkey", name: "Turkey", category: "holidays",
      palette: { ".": "#eaf7ff", "n": "#8b5a2b", "o": "#ff8c00", "r": "#c0392b", "y": "#ffe600", "k": "#1d1d2b" },
      rows: ["..r.y.o.y.r...",".ryy.oo.yy.r..",".ryyooooyyr...","..ryooooyr....","...nnnnnn.....","..nnnnnnnn....","..nnknnknn....","..nnnoonnn....","...nnnnnn.....","....nnnn......","...o.nn.o.....","..oo.nn.oo...."] },
    { id: "h-wreath", name: "Wreath", category: "holidays",
      palette: { ".": "#eaf7ff", "g": "#2e8b57", "r": "#c0392b", "y": "#ffe600" },
      rows: ["...gggggg.....","..ggggggggg...",".ggrggggrgg...",".gggggggggg...","ggg......ggg..","gg........gg..","gyg......gyg..","gg........gg..","ggg......ggg..",".gggggggggg...",".ggrggggrgg...","..ggggrgggg...","...gggggg....."] },
    { id: "h-stocking", name: "Stocking", category: "holidays",
      palette: { ".": "#eaf7ff", "r": "#c0392b", "w": "#ffffff", "g": "#2e8b57" },
      rows: [".wwwwwww......",".wwwwwww......",".rgrgrgr......",".rrrrrrr......",".rrrrrrr......",".rrrrrrr......",".rrrrrrr......",".rrrrrrr......",".rrrrrrrr.....",".rrrrrrrrrr...",".rrrrrrrrrrr..",".wwwrrrrrrrr..",".wwwwwwwwwww.."] },
    { id: "h-bell", name: "Bell", category: "holidays",
      palette: { ".": "#0c1430", "y": "#ffe600", "n": "#8b5a2b", "w": "#ffffff" },
      rows: ["......nn......",".....nwwn.....",".....yyyy.....","....yyyyyy....","...yyyyyyyy...","...yyyyyyyy...","..yyyyyyyyyy..","..yyyyyyyyyy..",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","wwwwwwwwwwwwww","......yy......",".....yyyy....."] },
    { id: "h-gingerbread-man", name: "Gingerbread Man", category: "holidays",
      palette: { ".": "#eaf7ff", "n": "#a0522d", "w": "#ffffff", "k": "#1d1d2b", "r": "#c0392b" },
      rows: ["....nnnnnn....","...nnnnnnnn...","...nknnnnkn...","...nnnnnnnn...","...nnrrrrnn...","n..nnnnnnnn..n","nnnnnnnnnnnnnn","nnnnnwnnwnnnnn","...nnnnnnnn...","...nnrrrrnn...","...nnn..nnn...","..nnnn..nnnn..","..nnn....nnn.."] },
    { id: "h-fireworks", name: "Fireworks", category: "holidays",
      palette: { ".": "#0c1430", "y": "#ffe600", "p": "#ff2e88", "c": "#00f0ff" },
      rows: ["......y.......","...p..y..p....","....p.y.p.....","y....ppp....y.",".yp.ppppp.py..","..ppppppppp...",".cppppppppppc.","..ppppppppp...",".yp.ppppp.py..","y....ppp....y.","....c.y.c.....","...c..y..c....","......y......."] },
    { id: "h-party-hat", name: "Party Hat", category: "holidays",
      palette: { ".": "#eaf7ff", "p": "#ff2e88", "c": "#00f0ff", "y": "#ffe600" },
      rows: ["......yy......",".....yppy.....",".....pppp.....","....ppccpp....","....pppppp....","...ppccppcp...","...pppppppp...","..ppccppccpp..","..pppppppppp..",".ppccppccppcp.",".pppppppppppp.","cccccccccccccc"] },

    // ===================== OBJECTS / TOYS =====================
    { id: "obj-crown", name: "Crown", category: "objects",
      palette: { ".": "#fff3f8", "y": "#ffe600", "r": "#ff2e88", "c": "#00f0ff" },
      rows: ["..r......r....",".rrr....rrr...","r.r.c..c.r.r..","yyyyyyyyyyyy..","yyyyyyyyyyyy..","yyryyyyyryy...","yyyyyyyyyyyy..","ycyyyyyyyycy..","yyyyyyyyyyyy..","yyyyyyyyyyyy.."] },
    { id: "obj-key", name: "Key", category: "objects",
      palette: { ".": "#0c1430", "y": "#ffe600", "k": "#1d1d2b" },
      rows: ["...yyyy.......","..yykkyy......",".yykkkkyy.....",".yykkkkyy.....","..yykkyy......","...yyyy.......","....yy........","....yy........","....yy........","....yyy.......","....yyy.......","....yy........","....yyy......."] },
    { id: "obj-padlock", name: "Padlock", category: "objects",
      palette: { ".": "#eaf7ff", "k": "#1d1d2b", "y": "#ffe600", "g": "#999999" },
      rows: ["...gggggg.....","..gg....gg....","..gg....gg....",".gg......gg...",".kkkkkkkkkk...",".kkkkkkkkkk...",".kkkkyykkkk...",".kkkkyykkkk...",".kkkkyykkkk...",".kkkkkkkkkk...",".kkkkkkkkkk...",".kkkkkkkkkk..."] },
    { id: "obj-sunglasses", name: "Sunglasses", category: "objects",
      palette: { ".": "#fff3f8", "k": "#1d1d2b", "c": "#00f0ff" },
      rows: ["..............",".kkkkk..kkkkk.","kkccckkkkcckk.","kkccckkkkcckk.","kkccckkkkcckk.",".kkccc..ccckk.","..kkkk..kkkk..","...kk....kk..."] },
    { id: "obj-top-hat", name: "Top Hat", category: "objects",
      palette: { ".": "#fff3f8", "k": "#1d1d2b", "r": "#c0392b" },
      rows: ["...kkkkkkkk...","...kkkkkkkk...","...kkkkkkkk...","...kkkkkkkk...","...kkkkkkkk...","...kkkkkkkk...","...rrrrrrrr...","...rrrrrrrr...",".kkkkkkkkkkkk.","kkkkkkkkkkkkkk","kkkkkkkkkkkkkk"] },
    { id: "obj-music-note", name: "Music Note", category: "objects",
      palette: { ".": "#eaf7ff", "p": "#ff2e88", "k": "#1d1d2b" },
      rows: ["......ppppp...","......ppppp...","......pp..pp..","......pp...pp.","......pp..pp..","......ppppp...","......pp......","......pp......","......pp......","...pppp.......",".ppppp........","ppppp.........",".ppp.........."] },
    { id: "obj-electric-guitar", name: "Electric Guitar", category: "objects",
      palette: { ".": "#0c1430", "r": "#c0392b", "k": "#1d1d2b", "w": "#ffffff" },
      rows: ["..........kk..",".........kkk..",".........wk...","........wk....",".......wk.....","...rr.wk......","..rrrwk.......",".rrrwrr.......",".rrwrrr.......",".rrrkrr.......",".rrrrrr.......","..rrrr........"] },
    { id: "obj-headphones", name: "Headphones", category: "objects",
      palette: { ".": "#fff3f8", "k": "#1d1d2b", "p": "#ff2e88" },
      rows: ["....kkkkkk....","..kkkkkkkkkk..",".kk........kk.",".kk........kk.","kk..........kk","kpk........kpk","kpk........kpk","kpk........kpk","kpk........kpk","kkk........kkk",".............."] },
    { id: "obj-book", name: "Book", category: "objects",
      palette: { ".": "#eaf7ff", "r": "#c0392b", "w": "#ffffff", "y": "#ffe600" },
      rows: [".rrrrrryrrrrr.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rwwwwwyrwwww.",".rrrrrryrrrrr.","..rrrrryrrrr.."] },
    { id: "obj-pencil", name: "Pencil", category: "objects",
      palette: { ".": "#eaf7ff", "y": "#ffe600", "n": "#8b5a2b", "k": "#1d1d2b", "p": "#ff2e88" },
      rows: ["...........pp.","..........pp..",".........yy...","........yyy...",".......yyy....","......nyy.....",".....nky......","....nky.......","...nky........","..nky.........",".nky..........","kky...........","k............."] },
    { id: "obj-lightbulb", name: "Lightbulb", category: "objects",
      palette: { ".": "#0c1430", "y": "#ffe600", "w": "#ffffff", "k": "#1d1d2b" },
      rows: ["....yyyyyy....","..yyyyyyyyyy..",".yyyyyyyyyyyy.",".yyywyyyywyyy.",".yyyyyyyyyyyy.",".yyyyyyyyyyyy.","..yyyyyyyyyy..","...yyyyyyyy...","....yyyyyy....","....kkkkkk....",".....kkkk.....",".....kkkk.....","......kk......"] },
    { id: "obj-camera", name: "Camera", category: "objects",
      palette: { ".": "#eaf7ff", "k": "#1d1d2b", "c": "#00f0ff", "y": "#ffe600" },
      rows: ["....kkkk......","...kkkkk......",".kkkkkkkkkkkk.","kkkkkkkkkkkkyk","kkkkccccckkkk.","kkkcccccckkkk.","kkkcccccckkkk.","kkkcccccckkkk.","kkkkccccckkkk.","kkkkkkkkkkkkk.",".kkkkkkkkkkkk."] },
    { id: "obj-dice", name: "Dice", category: "objects",
      palette: { ".": "#fff3f8", "w": "#ffffff", "k": "#1d1d2b", "r": "#c0392b" },
      rows: [".wwwwwwwwwww..",".wkkwwwwwkkw..",".wkkwwwwwkkw..",".wwwwwwwwwww..",".wwwwkkwwwww..",".wwwwkkwwwww..",".wwwwwwwwwww..",".wkkwwwwwkkw..",".wkkwwwwwkkw..",".wwwwwwwwwww..",".wwwwwwwwwww.."] },
    { id: "obj-teddy-bear", name: "Teddy Bear", category: "objects",
      palette: { ".": "#eaf7ff", "n": "#a0522d", "k": "#1d1d2b", "w": "#ffd9b3" },
      rows: ["..nn....nn....",".nnnn..nnnn...",".nnnnnnnnnn...",".nnknnnknnn...",".nnnnwwnnnn...",".nnnwkkwnnn...","..nnnwwnnn....",".nnnnnnnnnn...","nnnnwwwwnnnn..","nnnnwwwwnnnn..",".nnnnnnnnnn...","..nn....nn...."] },
    { id: "obj-magic-wand", name: "Magic Wand", category: "objects",
      palette: { ".": "#0c1430", "y": "#ffe600", "k": "#1d1d2b", "c": "#00f0ff" },
      rows: ["......y.......","....y.y.y.....",".....yyy......","...yyyyyyy....",".....yyy......","....y.yyk.....","......yk......",".......yk.....","........yk....",".........yk...","..........yk..","...........yk."] },
    { id: "obj-anchor", name: "Anchor", category: "objects",
      palette: { ".": "#eaf7ff", "g": "#999999", "k": "#1d1d2b" },
      rows: ["......gg......",".....gkkg.....",".....gkkg.....","......gg......","...gggggggg...","......gg......","......gg......","......gg......","g.....gg.....g","gg....gg....gg",".gg...gg...gg.","..ggggggggg...","....gggggg...."] },
    { id: "obj-treasure-chest", name: "Treasure Chest", category: "objects",
      palette: { ".": "#eaf7ff", "n": "#8b5a2b", "y": "#ffe600", "k": "#1d1d2b" },
      rows: ["..nnnnnnnnnn..",".nnnnnnnnnnnn.",".nyyyyyyyyyyn.",".nnnnnnnnnnnn.",".nnnnnkknnnnn.",".nyyyykkyyyyn.",".nyyyykkyyyyn.",".nyyyyyyyyyyn.",".nyyyyyyyyyyn.",".nnnnnnnnnnnn."] },
    { id: "obj-paint-palette", name: "Paint Palette", category: "objects",
      palette: { ".": "#eaf7ff", "w": "#ffd9b3", "r": "#ff2e88", "c": "#00f0ff", "y": "#ffe600", "g": "#2e8b57" },
      rows: ["...wwwwwww....","..wrrwwccww...",".wwrrwwccww...",".wwwwwwwwww...",".wyywwwwggw...",".wyywwwwggw...",".wwwwwwwwww...","..wwww..www...","...ww....ww..."] },

    // ===================== FACES =====================
    { id: "face-happy", name: "Happy Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyykkyyykkyyyy","yyykkyyykkyyyy","yyyyyyyyyyyyyy","yykkyyyyyykkyy","yykkkkkkkkkkyy","yyyykkkkkkyyyy","yyyyyyyyyyyyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-sad", name: "Sad Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "c": "#00f0ff" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyykkyyykkyyyy","yyykkyyykkyyyy","yycyyyyyyyyyyy","yycyyyyyyyyyyy","yyyyyyyyyyyyyy","yyyykkkkkkyyyy","yyykkyyyykkyyy","yykkyyyyyykkyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-wink", name: "Wink Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyykkyyyyyyyyy","yyykkyykkkkyyy","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yykkyyyyyykkyy","yykkkkkkkkkkyy","yyyykkkkkkyyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-heart-eyes", name: "Heart Eyes", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "r": "#ff2e88", "k": "#1d1d2b" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyrryyyyrryyyy","yrrrryyrrrryyy","yrrrryyrrrryyy","yyrrryyyrrryyy","yyyrryyyrryyyy","yykkyyyyyykkyy","yyykkkkkkkkyyy","yyyykkkkkkyyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-surprised", name: "Surprised Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyykkyyykkyyyy","yyykkyyykkyyyy","yyyyyyyyyyyyyy","yyyyykkkyyyyyy","yyyykkkkkyyyyy","yyyykkkkkyyyyy","yyyyykkkyyyyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-laughing", name: "Laughing Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "r": "#c0392b" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yykkkyyykkkyyy","ykyykyykyyykyy","yyyyyyyyyyyyyy","yykkkkkkkkkkyy","ykrrrrrrrrrrky","ykrrrrrrrrrrky","yykrrrrrrrrkyy","yyykkkkkkkkyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-sleepy", name: "Sleepy Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "c": "#00f0ff" },
      rows: ["...yyyyyyyy.c.",".yyyyyyyyyycc.","yyyyyyyyyyc.c.","yyyyyyyyyycc..","yykkkyyykkkyyy","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyyyykkkkyyyyy","yyyykkkkkkyyyy","yyyyyyyyyyyyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-silly", name: "Silly Tongue", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "r": "#ff2e88" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yyykkyyykkyyyy","yyyyyyyyyyyyyy","yyyyyyyyyyyyyy","yykkkkkkkkkkyy","yyyykkkkkkyyyy","yyyyyrrrryyyyy","yyyyyrrrryyyyy",".yyyyrrrryyyy.","...yyyyyyyy..."] },
    { id: "face-angry", name: "Angry Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "r": "#c0392b" },
      rows: ["...rrrrrrrr...",".rryyyyyyyyrr.","ryyyyyyyyyyyyr","ykkyyyyyyyykky","yyykkyyyykkyyy","yyyykkyykkyyyy","yyykkyyyykkyyy","yyyyyyyyyyyyyy","yyyykkkkkkyyyy","yyykkyyyykkyyy","yykkyyyyyykkyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
    { id: "face-crying", name: "Crying Face", category: "faces",
      palette: { ".": "#aee7ff", "y": "#ffd23f", "k": "#1d1d2b", "c": "#00f0ff" },
      rows: ["...yyyyyyyy...",".yyyyyyyyyyyy.","yyyyyyyyyyyyyy","yyykkyyykkyyyy","yyckkyyykkcyyy","yyckyyyyykcyyy","yyckyyyyykcyyy","yycyyyyyyycyyy","yyyyykkkkyyyyy","yyyykkyykkyyyy","yyykkyyyykkyyy",".yyyyyyyyyyyy.","...yyyyyyyy..."] },
  ];

  root.PIXEL_ONEOFFS = ONEOFFS;
  if (typeof module !== 'undefined' && module.exports) module.exports = ONEOFFS;
})(typeof window !== 'undefined' ? window : globalThis);
